#!/usr/bin/env bash
# install and configure HAProxy

# Install HAproxy on a server
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.6


sudo apt-get install -y haproxy=2.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo "
frontend myfrontend
        bind *:80
        default_backend myservers
backend myservers
        balance roundrobin
        server 154443-web-01 54.157.185.65 check
        server 154443-web-02 54.175.157.240 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

# Restart HAproxy service
sudo service haproxy restart
