#!/usr/bin/env bash
# Display "Best School" 10 times using a 'while' loop
# On the 9th iteration, displays "Hi" before "Best School"

i=0

while (( i < 10 ))
do
	echo "Best School"
	(( i++ ))
	if (( i == 9))
	then
		echo "Hi"
	fi
done
