#!/usr/bin/env bash
# Display "Best School" 10 times using a 'while' loop
# On the 4th iteration, displays "bad luck"
# On the 8th iteration, displays "good luck"

i=0

while (( i < 10 ))
do
	if (( i == 3 ))
	then
		echo "bad luck"
	elif (( i == 7 ))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i++ ))
done
