#!/usr/bin/env bash
# Displays numbers from 1 to 20
# On the 4th iteration, displays "4" and then "bad luck from China"
# On the 9th iteration, displays "8" and then "bad luck from Japan"
# On the 17th iteration, displays "17" and then "bad luck from Italy"

i=1
while (( i <= 20 ))
do
	echo "$i"
	case $i in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	(( i++ ))
done
